package site

// archiveStyles repaints every page under the history route on aged archive
// paper, marking the section itself rather than the age of the viewed report.
// Light mode also darkens the link teal one step (same hue) so link text keeps
// a contrast ratio of at least 4.5:1 on the darker paper; verified values —
// light: ink 9.99, ink-soft 4.73, link 4.96, up 6.43, down 5.00;
// dark: ink 12.27, ink-soft 5.83, link 6.59, up 4.82, down 6.89.
const archiveStyles = `<style>:root{--paper:#EAE0CA;--link:#0B6870}@media(prefers-color-scheme:dark){:root{--paper:#2A251E;--link:#5FB8C0}}</style>`

const styles = `<style>
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@400;500;700&family=Noto+Serif+TC:wght@500;600;700;900&display=swap');
:root{--paper:#F9F1E7;--ink:#33302E;--ink-soft:#66605A;--rule:#E0D8CA;--rule-heavy:#33302E;--up:#990F3D;--up-tint:#F2DCE2;--down:#1E6A45;--down-tint:#DFEBE0;--link:#0D7680;--band:#262A33;--band-ink:#C9C3BC;--serif:"Noto Serif TC","Songti TC","PMingLiU",serif;--sans:"Noto Sans TC","PingFang TC","Microsoft JhengHei",sans-serif}
@media(prefers-color-scheme:dark){:root{--paper:#201D1A;--ink:#EDE6DC;--ink-soft:#A89F94;--rule:#38342D;--rule-heavy:#EDE6DC;--up:#E5697F;--up-tint:#3B252A;--down:#6FBF8F;--down-tint:#22302A;--link:#5FB8C0;--band:#16130F;--band-ink:#C9C3BC}}
*{border-radius:0!important}body{margin:0!important;background:var(--paper)!important}.sy-main,.sy-app{max-width:none!important;padding:0!important;background:var(--paper)!important}.sy-html{margin:0!important}.briefast{box-sizing:border-box;background:var(--paper);color:var(--ink);font-family:var(--sans);font-size:15px;line-height:1.75;font-variant-numeric:tabular-nums}.briefast *{box-sizing:border-box}.briefast a{color:var(--link);text-decoration:none}.briefast a:hover{text-decoration:underline}.briefast.shell,.briefast .shell{max-width:1220px;margin:0 auto;padding-left:28px;padding-right:28px}.topbar{border-bottom:1px solid var(--rule);font-size:12.5px;color:var(--ink-soft);letter-spacing:.04em}.topbar-in{display:flex;justify-content:space-between;align-items:center;gap:16px;padding-top:9px;padding-bottom:9px;flex-wrap:wrap}.edition{display:flex;gap:14px;flex-wrap:wrap}.masthead{text-align:center;padding-top:30px;padding-bottom:22px}.masthead h1{font-family:var(--serif);font-weight:900;font-size:58px;line-height:1.1;letter-spacing:.015em;margin:0}.tagline{font-family:var(--serif);font-weight:500;font-size:16px;color:var(--ink-soft);letter-spacing:.3em;margin-top:8px;text-indent:.3em}.masthead-rule{border-top:3px solid var(--rule-heavy)}.masthead-rule:after{content:"";display:block;border-top:1px solid var(--rule-heavy);margin-top:2px}.dateline{display:flex;justify-content:center;gap:10px;flex-wrap:wrap;padding-top:9px;padding-bottom:9px;border-bottom:1px solid var(--rule);font-size:13px;letter-spacing:.06em;color:var(--ink-soft)}.dateline b{color:var(--ink)}.sep{color:var(--rule)}.nav-links{display:flex;gap:14px}
.archive-note{border-bottom:1px solid var(--rule)}.archive-note-in{display:flex;align-items:center;gap:14px;flex-wrap:wrap;padding-top:12px;padding-bottom:12px;font-size:13.5px}.archive-flag{background:var(--ink);color:var(--paper);font-weight:700;font-size:12.5px;letter-spacing:.08em;padding:2px 10px;flex-shrink:0}.archive-text{color:var(--ink)}.archive-links{margin-left:auto;display:flex;gap:16px;flex-wrap:wrap}.empty .gap{margin-left:18px}
.lead{display:grid;grid-template-columns:1fr 340px;gap:0 36px;padding:34px 0 38px}.lead-main{padding-right:36px;border-right:1px solid var(--rule)}.kicker{font-size:12.5px;font-weight:700;letter-spacing:.18em;color:var(--up);margin:0 0 10px}.headline{font-family:var(--serif);font-weight:700;font-size:33px;line-height:1.45;margin:0 0 18px}.standfirst{font-family:var(--serif);font-size:17.5px;line-height:1.9}.watch h2{font-size:14px;font-weight:700;letter-spacing:.14em;margin:0 0 12px;padding-top:8px;border-top:3px solid var(--rule-heavy)}.watch .md li{margin:0 0 12px}.section{padding:0 0 40px}.section-head{border-top:3px solid var(--rule-heavy);padding-top:10px;margin-bottom:22px;display:flex;align-items:baseline;gap:14px;flex-wrap:wrap}.section-head h2{font-family:var(--serif);font-weight:700;font-size:24px;margin:0}.note{font-size:13px;color:var(--ink-soft)}
.calls,.industries{display:grid;grid-template-columns:repeat(4,1fr);gap:0 32px}.call-col,.ind-col{padding-right:32px;border-right:1px solid var(--rule)}.call-col:last-child,.ind-col:last-child{padding-right:0;border-right:0}.call-col h3{margin:0 0 2px;padding-bottom:8px;font-size:15px;letter-spacing:.08em;display:flex;align-items:center;gap:8px}.call-col.up h3{color:var(--up);border-bottom:3px solid var(--up)}.call-col.down h3{color:var(--down);border-bottom:3px solid var(--down)}.tri{width:0;height:0;display:inline-block}.tri.u{border-left:5px solid transparent;border-right:5px solid transparent;border-bottom:9px solid var(--up)}.tri.d{border-left:5px solid transparent;border-right:5px solid transparent;border-top:9px solid var(--down)}.horizon{margin-left:auto;font-size:12px;color:var(--ink-soft)}.call-item{padding:14px 0}.stock{font-family:var(--serif);font-weight:700}.call-item .stock{font-size:18px}.call-col.up .stock{color:var(--up)}.call-col.down .stock{color:var(--down)}.code{font-family:var(--sans);font-size:13px;color:var(--ink-soft);margin-left:6px;letter-spacing:.05em}.why{font-size:14px;line-height:1.7;margin:6px 0 8px}.more,.srcs{font-size:13px}.no-call{color:var(--ink-soft);font-size:13px;margin-top:14px}.ind-col h3{margin:0 0 14px;padding-top:8px;border-top:3px solid var(--rule-heavy);font-size:15px;letter-spacing:.1em}.industry-event{margin:0 0 22px}.industry-event:last-of-type{margin-bottom:16px}.event-headline{font-family:var(--serif);font-size:17px;font-weight:700;line-height:1.45;margin:0 0 6px}.event-body p{font-family:var(--serif);font-size:15.5px;line-height:1.9;margin:0}.event-body li{margin-bottom:10px}
.news-list{border-top:1px solid var(--rule)}.news-entry{display:grid;grid-template-columns:260px 1fr;gap:0 36px;padding:24px 0;border-bottom:1px solid var(--rule)}.news-id .stock{font-size:21px}.stock-headline{font-family:var(--serif);font-size:16px;font-weight:600;line-height:1.5;margin:7px 0 10px}.tag{display:inline-flex;align-items:center;gap:6px;margin-top:0;padding:2px 10px;font-size:12.5px;font-weight:700;letter-spacing:.08em}.tag.up{color:var(--up);background:var(--up-tint)}.tag.down{color:var(--down);background:var(--down-tint)}.news-body p{font-family:var(--serif);font-size:15.5px;line-height:1.9;margin:0 0 10px}.news-body li{margin-bottom:2px}.entry-watch{margin-top:16px;padding-top:2px}.entry-watch-label{display:block;margin-bottom:6px;color:var(--ink-soft);font-size:12.5px;font-weight:700;letter-spacing:.14em}.entry-watch .md{color:var(--ink-soft);font-size:14px}.entry-watch .md p,.entry-watch .md li{font-family:var(--sans);font-size:14px;line-height:1.7}.entry-watch .md p,.entry-watch .md ul{margin-top:0;margin-bottom:0}.srcs{margin-top:14px}.srcs .lbl{color:var(--ink-soft);margin-right:8px}.srcs a,.srcs span{margin-right:14px}.hist-list{border-top:1px solid var(--rule)}.hist-item{display:grid;grid-template-columns:200px 1fr;gap:0 36px;padding:13px 0;border-bottom:1px solid var(--rule);font-size:14.5px}.hist-item .d{font-weight:700}.pager{display:flex;gap:4px;align-items:center;margin-top:18px;font-size:13.5px}.pager a,.pager .cur{padding:3px 11px}.pager .cur{background:var(--ink);color:var(--paper);font-weight:700}.history{padding-top:34px}.empty{padding-top:64px;padding-bottom:96px;text-align:center}.empty h2{font-family:var(--serif);font-size:28px}.site-foot{background:var(--band);color:var(--band-ink);margin-top:12px}.site-foot .shell{padding-top:30px;padding-bottom:34px}.foot-brand{font-family:var(--serif);font-weight:900;font-size:21px;color:#F2EDE6;margin:0 0 10px}.site-foot p{margin:0;font-size:13.5px;line-height:1.8;max-width:760px}
@media(max-width:1080px){.lead{grid-template-columns:1fr;gap:30px}.lead-main{padding-right:0;border-right:0}.calls,.industries{grid-template-columns:repeat(2,1fr);gap:26px 32px}.call-col:nth-child(2n),.ind-col:nth-child(2n){padding-right:0;border-right:0}.news-entry{grid-template-columns:200px 1fr}}
@media(max-width:767px){.briefast.shell,.briefast .shell{padding-left:18px;padding-right:18px}.masthead h1{font-size:40px}.tagline{font-size:14px;letter-spacing:.18em}.headline{font-size:25px}.standfirst{font-size:16px}.calls,.industries{grid-template-columns:1fr;gap:28px 0}.call-col,.ind-col{padding-right:0;border-right:0}.news-entry,.hist-item{grid-template-columns:1fr;gap:10px}}
</style>`
